const { scenarios, knowledge } = require("./ai-trainer-data");
const json=(statusCode,body)=>({statusCode,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"},body:JSON.stringify(body)});
const clamp=(n,min,max)=>Math.max(min,Math.min(max,Number(n)||0));
function extractText(data){if(typeof data.output_text==="string")return data.output_text;for(const item of data.output||[])for(const content of item.content||[])if(typeof content.text==="string")return content.text;return ""}
function parseModelJson(text){return JSON.parse(text.trim().replace(/^```json\s*/i,"").replace(/```$/i,"").trim())}
exports.handler=async(event)=>{
 if(event.httpMethod!=="POST")return json(405,{error:"Method not allowed"});
 if(!process.env.OPENAI_API_KEY)return json(500,{error:"У Netlify не налаштовано OPENAI_API_KEY"});
 let body;try{body=JSON.parse(event.body||"{}")}catch{return json(400,{error:"Некоректний запит"})}
 const {action,scenarioId,history=[],operatorText="",patience=0,conversion=0}=body;const s=scenarios[scenarioId];
 if(!s||!["start","turn"].includes(action))return json(400,{error:"Невідомий сценарій"});
 const [product,difficulty,person,persona,opening]=s;const facts=knowledge[product]||"Для цього універсального сценарію оцінюй техніку продажу без вигадування характеристик продукту.";
 const dialogue=Array.isArray(history)?history.slice(-12).map(m=>`${m.role==="operator"?"Оператор":"Клієнт"}: ${String(m.text||"").slice(0,900)}`).join("\n"):"";
 const instructions=`Ти рушій реалістичного тренажера продажів українською. Грай клієнта послідовно. Оцінюй продаж і комунікацію, не граматику. Для банківських продуктів суворо спирайся на базу фактів, не вигадуй тарифи й не заохочуй приховування ризиків. Не погоджуйся надто швидко. Відповідай лише валідним JSON без markdown.`;
 const base=`Продукт: ${product}. Складність: ${difficulty}. Клієнт: ${person}. Характер: ${persona}. Початкове заперечення: ${opening}.\nБаза знань: ${facts}`;
 const prompt=action==="start"?`${base}\nПочни короткою природною реплікою клієнта, використовуючи його заперечення, але не копіюй механічно. JSON: {"client_reply":"...","client_mood":"нейтральний|скептичний|роздратований"}`:`${base}\nТерпіння ${clamp(patience,0,100)}/100, готовність ${clamp(conversion,0,100)}/100. Відповідь оператора: ${String(operatorText).slice(0,1200)}\nДіалог:\n${dialogue}\nОціни 0-10. Поверни 1-3 реально застосовані техніки лише з переліку: Активне слухання, Емпатія, Уточнення потреби, SPIN, Аргументація цінністю, Робота із запереченням, Прозорість умов, Закриття угоди. Фідбек одним практичним реченням. Штрафуй неправдиві банківські твердження. patience_delta -25..12, trust_delta 0..20. JSON: {"score":0,"techniques":["..."],"feedback":"...","patience_delta":0,"trust_delta":0,"client_mood":"скептичний|роздратований|пом'якшується|зацікавлений|переконаний","client_reply":"..."}`;
 try{const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${process.env.OPENAI_API_KEY}`},body:JSON.stringify({model:process.env.OPENAI_MODEL||"gpt-4.1-mini",instructions,input:prompt,max_output_tokens:550,temperature:.72})});const data=await response.json();if(!response.ok){console.error("OpenAI",response.status,data);return json(response.status,{error:response.status===429?"Закінчився баланс API або перевищено ліміт":"OpenAI не зміг відповісти"})}const result=parseModelJson(extractText(data));if(action==="turn"){result.score=clamp(result.score,0,10);result.patience_delta=clamp(result.patience_delta,-25,12);result.trust_delta=clamp(result.trust_delta,0,20);if(!Array.isArray(result.techniques))result.techniques=[result.technique||"Робота із запереченням"]}return json(200,result)}catch(error){console.error(error);return json(500,{error:"Не вдалося обробити відповідь AI. Спробуйте ще раз."})}
};
