const fs = require("fs");
const assert = require("assert");

const backend = fs.readFileSync("backend/server.py", "utf8");
const admin = fs.readFileSync("frontend/src/pages/Admin.jsx", "utf8");
const goals = fs.readFileSync("frontend/src/pages/Goals.jsx", "utf8");
const creditGoals = fs.readFileSync("frontend/src/pages/CreditGoals.jsx", "utf8");
const app = fs.readFileSync("frontend/src/App.js", "utf8");
const fn = fs.readFileSync("netlify/functions/google-goals.js", "utf8");
const appsScript = fs.readFileSync("integrations/google-sheets/Code.gs", "utf8");

assert(backend.includes("goals_login: Optional[str] = None"));
assert(backend.includes('updates["goals_login"] = normalized_goals_login or None'));
assert(backend.includes("Цей ключ Google цілей уже використовується"));
assert(admin.includes('data-testid="user-edit-goals-login"'));
assert(goals.includes("/.netlify/functions/google-goals"));
assert(goals.includes('navigate("/goals/credit")'));
assert(app.includes('path="/goals/credit"'));
assert(creditGoals.includes('label: "X-Sell"'));
assert(creditGoals.includes('label: "Web Apps"'));
assert(creditGoals.includes('label: "INB"'));
assert(creditGoals.includes('label: "Місяць"'));
assert(creditGoals.includes('label: "Вчора"'));
assert(creditGoals.includes('metric.rule === "aht15"'));
assert(creditGoals.includes('metric.rule === "projective100"'));
assert(fn.includes("user.goals_login"));
assert(fn.includes('url.searchParams.set("goals_login", goalsLogin)'));
assert(fn.includes("credit_metrics"));
assert(appsScript.includes('normalizedHeaders.indexOf("goals_login")'));
assert(appsScript.includes("CREDIT_METRICS_SHEET_NAME"));
console.log("Google goals + credit details integration checks: PASS");
