import {
  Backpack, Badge, Bird, BookOpen, Bug, Cable, Camera, Circle, CircleDot, Clock3,
  Coffee, Cog, Compass, Crown, Dice5, Disc3, Drill, Feather, Flame, Flashlight,
  Footprints, Frame, Glasses, Globe2, Headphones, Hourglass, KeyRound, LockKeyhole,
  Mail, Origami, Package, Paintbrush, Paperclip, PenLine, Rocket, Ruler, Sailboat,
  Scissors, Search, Skull, SprayCan, Spade, Sprout, Stamp, Star, Ticket, Trophy,
  Umbrella, Usb, Utensils, Watch, Wine, Wrench,
} from "lucide-react";

const ICONS = {
  backpack: Backpack,
  badge: Badge,
  bird: Bird,
  book: BookOpen,
  bug: Bug,
  cable: Cable,
  camera: Camera,
  circle: Circle,
  "circle-dot": CircleDot,
  clock: Clock3,
  coffee: Coffee,
  cog: Cog,
  compass: Compass,
  crown: Crown,
  dice: Dice5,
  disc: Disc3,
  drill: Drill,
  feather: Feather,
  flame: Flame,
  flashlight: Flashlight,
  footprints: Footprints,
  frame: Frame,
  glasses: Glasses,
  globe: Globe2,
  headphones: Headphones,
  hourglass: Hourglass,
  key: KeyRound,
  lock: LockKeyhole,
  mail: Mail,
  origami: Origami,
  box: Package,
  paintbrush: Paintbrush,
  paperclip: Paperclip,
  pen: PenLine,
  rocket: Rocket,
  ruler: Ruler,
  sailboat: Sailboat,
  scissors: Scissors,
  search: Search,
  skull: Skull,
  "spray-can": SprayCan,
  spade: Spade,
  sprout: Sprout,
  stamp: Stamp,
  star: Star,
  ticket: Ticket,
  trophy: Trophy,
  umbrella: Umbrella,
  usb: Usb,
  utensils: Utensils,
  watch: Watch,
  wine: Wine,
  wrench: Wrench,
};

export default function ObjectIcon({ name, size = 20, strokeWidth = 2.7, ...props }) {
  const Icon = ICONS[name] || Search;
  return <Icon size={size} strokeWidth={strokeWidth} aria-hidden="true" {...props} />;
}
