// Demo users (login credentials)
export const DEMO_USERS = [
  {
    email: "anna@callhub.ua",
    password: "demo123",
    name: "Анна Коваль",
    role: "Оператор",
    department: "Продажі • Зміна А",
    avatarInitials: "АК",
    avatarColor: "#FFB800",
    level: 7,
    xp: 1240,
    xpToNext: 2000,
    balance: 3450,
    totalEarned: 12980,
    streak: 5,
    achievements: [
      { id: "a1", title: "7 днів поспіль", icon: "flame", color: "#FF5C00", unlocked: true },
      { id: "a2", title: "Топ-3 місяця", icon: "trophy", color: "#FFB800", unlocked: true },
      { id: "a3", title: "Майстер холодних дзвінків", icon: "phone", color: "#39FF14", unlocked: true },
      { id: "a4", title: "Наставник", icon: "graduation-cap", color: "#00F0FF", unlocked: false },
      { id: "a5", title: "Ідеальний тиждень", icon: "sparkles", color: "#FFB800", unlocked: false },
    ],
  },
  {
    email: "maks@callhub.ua",
    password: "demo123",
    name: "Максим Дубенко",
    role: "Senior оператор",
    department: "Підтримка • Зміна B",
    avatarInitials: "МД",
    avatarColor: "#00F0FF",
    level: 12,
    xp: 780,
    xpToNext: 3000,
    balance: 6120,
    totalEarned: 24500,
    streak: 12,
    achievements: [
      { id: "a1", title: "30 днів поспіль", icon: "flame", color: "#FF5C00", unlocked: true },
      { id: "a2", title: "№1 місяця", icon: "crown", color: "#FFB800", unlocked: true },
      { id: "a3", title: "Наставник", icon: "graduation-cap", color: "#00F0FF", unlocked: true },
      { id: "a4", title: "Ідеальний тиждень", icon: "sparkles", color: "#FFB800", unlocked: true },
      { id: "a5", title: "Тисячник дзвінків", icon: "phone", color: "#39FF14", unlocked: false },
    ],
  },
];

// Daily quests
export const DAILY_QUESTS = [
  {
    id: "q1",
    title: "Прийняти 20 дзвінків",
    description: "Без пропусків до кінця зміни",
    difficulty: "easy",
    reward: 50,
    progress: 14,
    goal: 20,
    icon: "phone-call",
  },
  {
    id: "q2",
    title: "Оцінка 5 від клієнта",
    description: "Отримай мінімум одну відмінну оцінку",
    difficulty: "medium",
    reward: 120,
    progress: 0,
    goal: 1,
    icon: "star",
  },
  {
    id: "q3",
    title: "0 запізнень цього тижня",
    description: "Тримай темп до п'ятниці",
    difficulty: "medium",
    reward: 150,
    progress: 3,
    goal: 5,
    icon: "clock",
  },
  {
    id: "q4",
    title: "Допомогти новачку",
    description: "Проведи 15 хв менторства",
    difficulty: "hard",
    reward: 250,
    progress: 15,
    goal: 15,
    icon: "graduation-cap",
  },
  {
    id: "q5",
    title: "Закрити 3 складні кейси",
    description: "Ескалації або довгі клієнти",
    difficulty: "hard",
    reward: 300,
    progress: 1,
    goal: 3,
    icon: "target",
  },
  {
    id: "q6",
    title: "Оновити CRM без помилок",
    description: "Всі картки клієнтів заповнені",
    difficulty: "easy",
    reward: 40,
    progress: 8,
    goal: 8,
    icon: "check-circle-2",
  },
];

// Prize store
export const PRIZES = [
  {
    id: "p1",
    title: "Худі CallHub",
    description: "Фірмовий чорний худі з логотипом",
    price: 2500,
    category: "merch",
    image: "https://images.pexels.com/photos/28701952/pexels-photo-28701952.jpeg",
    stock: 12,
  },
  {
    id: "p2",
    title: "Додатковий вихідний",
    description: "1 оплачуваний вихідний день",
    price: 5000,
    category: "privilege",
    image: null,
    icon: "calendar-off",
    stock: 5,
  },
  {
    id: "p3",
    title: "Сертифікат Rozetka 500 ₴",
    description: "На будь-які покупки",
    price: 3000,
    category: "certificate",
    image: null,
    icon: "gift",
    stock: 20,
  },
  {
    id: "p4",
    title: "Вибір своєї зміни",
    description: "На один тиждень обирай сам",
    price: 2200,
    category: "privilege",
    image: null,
    icon: "clock-4",
    stock: 8,
  },
  {
    id: "p5",
    title: "Mystery Box",
    description: "Випадковий приз з каталогу",
    price: 1500,
    category: "merch",
    image: "https://images.unsplash.com/photo-1767522248089-468ec2d4efd7",
    stock: 15,
  },
  {
    id: "p6",
    title: "Довга перерва +30 хв",
    description: "Одноразово, на будь-який день",
    price: 900,
    category: "privilege",
    image: null,
    icon: "coffee",
    stock: 30,
  },
  {
    id: "p7",
    title: "Сертифікат Rozetka 1000 ₴",
    description: "На будь-які покупки",
    price: 5800,
    category: "certificate",
    image: null,
    icon: "gift",
    stock: 10,
  },
  {
    id: "p8",
    title: "Кружка CallHub",
    description: "Керамічна з неоновим принтом",
    price: 800,
    category: "merch",
    image: "https://images.pexels.com/photos/33629664/pexels-photo-33629664.jpeg",
    stock: 25,
  },
];

export const PRIZE_CATEGORIES = [
  { id: "all", label: "Все" },
  { id: "merch", label: "Мерч" },
  { id: "privilege", label: "Привілеї" },
  { id: "certificate", label: "Сертифікати" },
];
